In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('data/mul_lin_reg.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [34]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [35]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [36]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [37]:
reg.intercept_

0.29603261264909486

In [39]:
reg.score(x,y)

0.4066811952814283

In [50]:
r2 = reg.score(x,y)
n, p = x.shape
adj_r2 = 1 - (1-r2)*(n-1)/(n-p-1)
adj_r2 # adjusted r2 considerably lower than r2; one of the features is trash.

0.3920313482513401

# f-regression

figuring out which features are trash

In [51]:
from sklearn.feature_selection import f_regression

In [52]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [54]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [55]:
p_values.round(3)

array([0.   , 0.676])

# Summary table

In [56]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])

In [58]:
reg_summary['Coeffs'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [59]:
reg_summary

Features    Coeffs  p-values
0         SAT  0.001654     0.000
1  Rand 1,2,3 -0.008270     0.676

# standardization

In [60]:
from sklearn.preprocessing import StandardScaler

In [61]:
scaler = StandardScaler()

In [62]:
scaler.fit(x)

StandardScaler()

In [63]:
x_scaled = scaler.transform(x)

In [65]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [66]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [67]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [68]:
reg.intercept_

3.330238095238095

In [72]:
reg_summary = pd.DataFrame([['Bias'],['Sat'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights']=reg.intercept_,reg.coef_[0],reg.coef_[1]
reg_summary

Features   Weights
0        Bias  3.330238
1         Sat  0.171814
2  Rand 1,2,3 -0.007030

# Predicting with standardized weights

In [73]:
new_data = pd.DataFrame(data=[[1700, 2],[1800,1]],columns=['SAT', 'Rand 1,2,3'])

In [74]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [75]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])